### ISSUE TITLE
Camera recognition isn't working

### ISSUE THREAD

**Issue by thunyasilps** [Passiolife/Passio-Nutrition-AI-Flutter-SDK-Distribution#1]
I try to run example file. I am actually not sure if I miss anything. This is what I did:
1) add nutrition_ai: ^3.1.4+1
2) Add the camera permissions to your Info.plist file
3) flutter pub get

There is also some error that I comment it out:
1) I am not sure what is ADVISOR_KEY
2) FoodAnalysisPage is not found

Camera permission is granted but no food is detected. It just shows circular progress saying Searching. Did I do anything wrong?

![IMG_829F53E8D2B9-1](https://github.com/user-attachments/assets/08970224-c595-4896-a712-cb15e245d6a1)

**Comment by drstarson** [comment]
@thunyasilps Thank you for reporting. Quick question: have you connected with Ipsita and Marin on our team? What company are you with? We'll reach out via Slack to make sure we can support you directly. 

@marinPassio quick FYI.

**Comment by thunyasilps** [comment]
I am with Diagnose Health, and I haven't connected with Ipsita or Marin. I am also not aware of Slack. Do you have a Slack community for Nutrition AI? Where can I find it?

**Comment by ipsita0709** [comment]
@thunyasilps 

As @sahilmind mentioned in Slack, the example project should work directly without any additional configuration. Sahil has updated the code in the repository, so please pull the latest changes and try running it again.

If you have any further questions or need assistance, feel free to reach out in Slack. Please also update us on whether the issue has been resolved for you.

**Comment by drstarson** [comment]
@thunyasilps @sahilmind if the issue is resolved, please close the ticket.
